pr для ревью
DKhromov1993/AndroidAcademy pull request #6
Opened 2018-10-11 20:48 UTC by DKhromov1993

2018-10-16 12:28 UTC, xanderblinov requested changes
добавил комментариев

2018-10-16 12:28 UTC, xanderblinov commented on app/src/main/java/com/example/den/androidacademyhomework/NewsListActivity.java
> +        VerticalSpaceItemDecoration itemDecoration1 = new VerticalSpaceItemDecoration(4);
зачем 1 в itemDecoration1 ?

2018-10-16 12:28 UTC, xanderblinov commented on app/src/main/java/com/example/den/androidacademyhomework/NewsListActivity.java
> +        context = this;
зачем? можно просто всегда обращаться к this

2018-10-16 12:28 UTC, xanderblinov commented on app/src/main/res/values/strings.xml
> +    <string name="hint_news_title">Носороги искусали человека, когда тот жевал колбасу из чермондера</string>
😂

2018-10-16 12:28 UTC, xanderblinov commented on app/src/main/res/values/strings.xml
> +    <string name="hint_news_text">Лорем ипсумЛорем ипсумЛорем ипсумЛорем ипсумЛорем ипсумЛорем ипсумЛорем ипсумЛорем ипсумЛорем ипсум</string>
поищи, должна быть стринга в андроид ресурсах

2018-10-16 12:28 UTC, xanderblinov commented on app/src/main/res/layout/activity_about.xml
> +            android:layout_marginLeft="10dp"
обычно выносим в dimen как отдельные ресурсы c названием типа dp_10

2018-10-16 12:28 UTC, xanderblinov commented on app/src/main/res/layout/activity_news_list.xml
> +    </android.support.v7.widget.RecyclerView>
лучше просто блок android.support.v7.widget.RecyclerView закрыть как 

```
<android.support.v7.widget.RecyclerView
        android:id="@+id/rv_news"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical"/>
```

2018-10-16 12:28 UTC, xanderblinov commented on app/src/main/res/layout/news_item.xml
> +    <androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
```xmlns:android="http://schemas.android.com/apk/res/android"```

лишняя

2018-10-16 12:31 UTC, xanderblinov commented on app/src/main/java/com/example/den/androidacademyhomework/NewsListActivity.java
> +        newsAdapter = new NewsAdapter(this, DataUtils.generateNews());
Надо отделить создание от ```DataUtils.generateNews()```

2018-10-16 12:32 UTC, xanderblinov reviewed
Элементы надо создавать не в конструкторе адаптера а добавлять туда.

2018-10-17 20:08 UTC, DKhromov1993 commented on app/src/main/res/layout/activity_about.xml
> +            android:layout_marginLeft="10dp"
а нужно ли выносить все? Или достаточно вынести только часто используемые?

2018-10-17 20:39 UTC, DKhromov1993 commented on app/src/main/java/com/example/den/androidacademyhomework/NewsListActivity.java
> +        context = this;
Когда вешаю listener на элемент списка - там this будет OnItemClickListener

private final NewsAdapter.OnItemClickListener onItemClickListener = new NewsAdapter.OnItemClickListener() {
        @Override
        public void onItemClick(NewsItem newsItem) {
            AboutActivity.start((Activity) context,
                    newsItem.getImageUrl(),
                    newsItem.getCategory().getName(),
                    newsItem.getFullText(),
                    newsItem.getPublishDate("MMM d HH:mm"),
                    newsItem.getTitle()
            );
        }
    };

2018-10-17 20:45 UTC, DKhromov1993 commented on app/src/main/java/com/example/den/androidacademyhomework/NewsListActivity.java
> +        VerticalSpaceItemDecoration itemDecoration1 = new VerticalSpaceItemDecoration(4);
Экспериментировал видимо и не убрал :(

2018-10-19 06:21 UTC, xanderblinov reviewed
докинул на подумать. предлагаю попробовать recycler с несколькими типами элементов. Например, один тип, это реклама и реклама - это каждый третий элемент (ну или первый, для простоты)

2018-10-19 06:21 UTC, xanderblinov commented on app/build.gradle
> +    implementation 'com.android.support:appcompat-v7:28.0.0'
28.0.0 обычно выносят в переменную, чтобы случайно не получилось несогласованной версии

2018-10-19 06:21 UTC, xanderblinov commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".AboutActivity"></activity>
можно сделать тэг просто `<activity android:name=".AboutActivity"/>`

2018-10-19 06:21 UTC, xanderblinov commented on app/src/main/java/com/example/den/androidacademyhomework/AboutActivity.java
> +        intent.putExtra(KEY_IMG, imgUrl);
лучше не сериализовать по отдельности, а сохранить как один объект. Прикинь, как будет выглядеть еод, если будет у класса 30 полей

2018-10-19 06:21 UTC, xanderblinov commented on app/src/main/java/com/example/den/androidacademyhomework/AboutActivity.java
> +        intent.putExtra(KEY_IMG, imgUrl);
для этого обычно используют Serializable. Но не забудь про контракт с SerialVersionUID

2018-10-19 06:21 UTC, xanderblinov commented on app/src/main/java/com/example/den/androidacademyhomework/NewsAdapter.java
> +    void setOnItemClickListener(final OnItemClickListener mItemClickListener) {
обычно его передают как параметр конструктора

2018-10-19 06:21 UTC, xanderblinov commented on app/src/main/java/com/example/den/androidacademyhomework/NewsListActivity.java
> +                    newsItem.getPublishDate("MMM d HH:mm"),
коснстанта, ее обычно выносят

2018-10-19 06:21 UTC, xanderblinov commented on app/src/main/res/layout/activity_about.xml
> +    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
лишняя схема, уже определена в родителе

2018-10-19 06:21 UTC, xanderblinov commented on app/src/main/res/layout/activity_about.xml
> +        tools:context=".AboutActivity">
контекст уже определен в родителе. Кстати подумай, зачем он нужен

2018-10-19 06:21 UTC, xanderblinov commented on app/src/main/res/layout/activity_news_list.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
а тебе нужен этот linearLayout? Лучше сделать корневым RecyclerView

2018-10-19 06:21 UTC, xanderblinov commented on app/src/main/res/layout/news_item.xml
> +    android:background="#F7F8F5"
а точно нужен этот layout с бэкграундом? может лучше его убрать а бэкграунд оставить на совесть recycler?

2018-10-19 06:21 UTC, xanderblinov commented on app/src/main/res/layout/news_item.xml
> +        app:cardCornerRadius="2dp"
такие вещи обычно выносятся. потом дизайнер говорит, давайте быстренько везде поменяем углы у карточек и меняем в одном месте

2018-10-19 06:21 UTC, xanderblinov commented on app/src/main/res/layout/news_item.xml
> +                android:layout_width="250dp"
заданная ширина у текста? зачем? С учетом 245dp на элементе ниже - выглядит, как какой-то костыль

нужно стараться делать все в относительных размерах. кроме отступов, разумеется

2018-11-24 21:16 UTC, merged